### ISSUE TITLE
Replace Quantified Code

### ISSUE THREAD

**Issue by cyprieng** [Trax-air/swagger-tester#33]
QuantifiedCode will be shutting down on October 1st 2016, so we should find an alternative.

Any idea ? Maybe just run flake8 on travis ?

**Comment by beanqueen** [comment]
that is sad, i kind of like it. i'm totally ok with flake8, though. it's already added in my pr.

**Comment by cyprieng** [comment]
Yes me too...
Let's stick to flake8
