### ISSUE TITLE
Faker?

### ISSUE THREAD

**Issue by ghost** [Trax-air/swagger-tester#34]
Hi
Is it possible/would it be worthy of adding faker generated data?
probably in 

```
def _get_example_from_basic_type(type):
```

? 
Or is there a way to auto generate random Faker data for basic type I missed?

**Comment by cyprieng** [comment]
Swagger_parser allow this: https://github.com/Trax-air/swagger-parser/blob/master/swagger_parser/swagger_parser.py#L84

**Comment by ghost** [comment]
is there a reason for swagger_tester to force use_example=False when app_url is used?

```
    elif app_url is not None:
        app_client = requests
        swagger_parser = SwaggerParser(swagger_dict=requests.get(
            u'{0}/swagger.json'.format(app_url)).json(),
                                       use_example=False)
```

**Comment by ghost** [comment]
#35
