### ISSUE TITLE
OS X -- Testing under Python 3.6 -- issue with setup_requires

### ISSUE THREAD

**Issue by ssteinerx** [Trax-air/swagger-tester#43]
Just adding `py36` to `envlist` in tox.ini should be enough to run the tests under Python 3.6.

But, apparently due to the way that `setup_requires` handles installation of `pytest-runner`, this leads to one of these beauties:
```
Processing ./.tox/dist/swagger_tester-0.2.7.zip
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/pytest-runner/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) -- Some packages may not be found!
    Couldn't find index page for 'pytest-runner' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) -- Some packages may not be found!
    No local packages or working download links found for pytest-runner
```

`pip` will install the same package just fine.

Issue is mentioned here:

https://github.com/pypa/pip/issues/4156

And some tips here about overcoming the issues here:

https://pip.pypa.io/en/stable/reference/pip_install/#controlling-setup-requires

And some info about 3.6 bundling its own openssl and, so not using the (oddball) OS trust bundle etc. is here:

https://bugs.python.org/issue28150

Not sure where to go from here, but swagger-tester can't `tox` itself under 3.6 on OS X.

**Comment by flavianh** [comment]
I'm sorry I can't reproduce it.

Here's the tox file I used:

```
[tox]
envlist = py36

[testenv]
setenv =
    PYTHONPATH = {toxinidir}:{toxinidir}/swagger_tester
commands = python setup.py test
```

I installed tox with `pip install -U tox`

and the `tox` command runs fine 

My macosX version is 10.12.4

**Comment by riebling** [comment]
Trying a fresh clone into my probably-still-dirty Python environment, and to quote another person on the internet, got this gem:
```
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-IbKnJc/pylint/
You are using pip version 8.1.1, however version 18.0 is available.                                                                         
You should consider upgrading via the 'pip install --upgrade pip' command.
Makefile:13: recipe for target 'install' failed
make: *** [install] Error 1
```
Which I worked around by adding `--disable-pip-version-check` to the pip commands in Makefile.
Next error:
```
Collecting pylint (from -r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/04/1f/1d3929051b45c3e4015178c5fe5bbee735fb4e362e0fc4f0fbf3f68647ad/pylint-2.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Couldn't find index page for 'pytest-runner' (maybe misspelled?)
    No local packages or download links found for pytest-runner
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-HYddby/pylint/setup.py", line 177, in <module>
        install()
      File "/tmp/pip-build-HYddby/pylint/setup.py", line 174, in install
        **kwargs)
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "build/bdist.linux-i686/egg/setuptools/dist.py", line 260, in __init__
      File "build/bdist.linux-i686/egg/setuptools/dist.py", line 284, in fetch_build_eggs
      File "build/bdist.linux-i686/egg/pkg_resources.py", line 563, in resolve
      File "build/bdist.linux-i686/egg/pkg_resources.py", line 799, in best_match
      File "build/bdist.linux-i686/egg/pkg_resources.py", line 811, in obtain
      File "build/bdist.linux-i686/egg/setuptools/dist.py", line 327, in fetch_build_egg
      File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py", line 434, in easy_install

      File "build/bdist.linux-i686/egg/setuptools/package_index.py", line 475, in fetch_distribution
    AttributeError: 'NoneType' object has no attribute 'clone'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-HYddby/pylint/
Makefile:13: recipe for target 'install' failed
make: *** [install] Error 1
```
This is all interesting in terms of helping a wider base of users who wish to install BOOM into generic possibly-unknown Python environments. It's good to make the install process more robust. But maybe I should be testing in a cleaner environment where we plan to run, like a standard Amazon Machine Image running approved Amazon Linux with Docker support. It's ironic because Python supports such clean and simple coding, but it's growth and popularity have led to feature creep of the kind that breaks backwards and cross-platform compatibility :-/ (I should write up a boilerplate "Why doesn't Python Just Work for Eric" :) )
