### ISSUE TITLE
Can I use swagger-tester for cherrypy framework? 

### ISSUE THREAD

**Issue by pradeepYogesh** [Trax-air/swagger-tester#44]
This is Beacuse I require Connexion to use swagger-tester. I intend to use swagger-tester for REST api already designed using cherrypy framework

**Comment by cyprieng** [comment]
Yes you can use it for any swagger api: `swagger_test(app_url='http://petstore.swagger.io/v2', authorize_error=authorize_error)`, you just need to start your web app before.
